### PR TITLE
Add display option documentation

### PR DESCRIPTION
**Pull request by TrySound**
Everything seems fine now. Let's publish `v1.0.0`.

### CODE REVIEW

**Comment by seaneking** [comment]
Great thanks. I think a minor is more appropriate, since this repo is all of 40 commits old and could use more thorough tests.

**Comment by TrySound** [comment]
I talk about semver. Your 0.3 is not minor at all.

**Comment by TrySound** [comment]
@seaneking Read please http://semver.org/.

**Comment by TrySound** [comment]
@seaneking It's part of postcss guideline https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#43-maintain-a-changelog
You should follow semver.

**Comment by TrySound** [comment]
And tests are fine. I prepared everything for 1.0.

**Comment by seaneking** [comment]
I know how semver works. You should only bump a major version when there are breaking changes in the public API, adding a small feature and making non-breaking clean ups qualifies as a minor version.

**Comment by TrySound** [comment]
@seaneking I mean that 0.* versions are not semver. That's why npm do not trust it and updates only patch. So technically you made something like "major update". And still this is not semver. You should start using 1.* since start of the project.

**Pull request merged**
